#!/bin/sh

git filter-branch --env-filter '
WRONG_EMAIL="wrong@mail.com"
NEW_NAME="fireflaredb"
NEW_EMAIL="correct@mail.com"

if [ "$GIT_COMMITTER_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$NEW_NAME"
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$WRONG_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$NEW_NAME"
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' -f --tag-name-filter cat -- --branches --tags
